//
//  LRTSDBDiscoverCategoryModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/9.
//

#import "LRTSDBDiscoverCategoryModel.h"

@implementation LRTSDBDiscoverCategoryModel

//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )


//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )

@end
