//
//  LRTSDBAudioModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/10.
//

#import "LRTSDBAudioModel.h"

@implementation LRTSDBAudioModel

WCDB_IMPLEMENTATION(LRTSDBAudioModel)

WCDB_SYNTHESIZE(LRTSDBAudioModel, audioName)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioPath)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioDesc)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioSecondsCount)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioSize)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioCreateTime)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioGroupId)
WCDB_SYNTHESIZE(LRTSDBAudioModel, fileId)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioUserId)
WCDB_SYNTHESIZE(LRTSDBAudioModel, audioUserNick)
WCDB_SYNTHESIZE(LRTSDBAudioModel, pStatus)


//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
////
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )
//WCDB_SYNTHESIZE(LRTSDBAudioModel, )

@end
