//
//  LRTSDBEntityModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/9.
//

#import "LRTSDBEntityModel.h"

@implementation LRTSDBEntityModel

WCDB_IMPLEMENTATION(LRTSDBEntityModel)


WCDB_SYNTHESIZE(LRTSDBEntityModel,et_id)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_name)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_desc)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_cover)

WCDB_SYNTHESIZE(LRTSDBEntityModel,et_type)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_sort)
//WCDB_SYNTHESIZE(LRTSDBEntityModel,et_tag)
//WCDB_SYNTHESIZE(LRTSDBEntityModel,et_attatchAd)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_attatchModel)
WCDB_SYNTHESIZE(LRTSDBEntityModel,et_umCountName)
WCDB_SYNTHESIZE(LRTSDBEntityModel,author)
WCDB_SYNTHESIZE(LRTSDBEntityModel,playCount)
WCDB_SYNTHESIZE(LRTSDBEntityModel,userCount)
WCDB_SYNTHESIZE(LRTSDBEntityModel,contentCount)
WCDB_SYNTHESIZE(LRTSDBEntityModel,userState)
WCDB_SYNTHESIZE(LRTSDBEntityModel,strategy)

//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
////
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//WCDB_SYNTHESIZE(LRTSDBEntityModel, )

@end
