//
//  LRTSDBEntityModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/9.
//

#import "LRTSDBEntityModel.h"

@implementation LRTSDBEntityModel

WCDB_IMPLEMENTATION(LRTSDBEntityModel)

WCDB_SYNTHESIZE(LRTSDBEntityModel, et_id)
WCDB_SYNTHESIZE(LRTSDBEntityModel, et_name)
WCDB_SYNTHESIZE(LRTSDBEntityModel, et_desc)
WCDB_SYNTHESIZE(LRTSDBEntityModel, et_cover)

WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
//
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )
WCDB_SYNTHESIZE(LRTSDBEntityModel, )

@end
