//
//  LRTSBook.m
//  Kiwi
//
//  Created by Jack Bai on 2017/11/1.
//

#import "LRTSBook.h"

@implementation LRTSBook

WCDB_IMPLEMENTATION(LRTSBook)

WCDB_SYNTHESIZE(LRTSBook, bId)
WCDB_SYNTHESIZE(LRTSBook, hot)
WCDB_SYNTHESIZE(LRTSBook, sections)
WCDB_SYNTHESIZE(LRTSBook, state)

//WCDB_SYNTHESIZE(LRTSBook, sort)

WCDB_SYNTHESIZE(LRTSBook, commentCount)
WCDB_SYNTHESIZE(LRTSBook, isMarked)

WCDB_SYNTHESIZE(LRTSBook, name)
WCDB_SYNTHESIZE(LRTSBook, author)
WCDB_SYNTHESIZE(LRTSBook, announcer)
WCDB_SYNTHESIZE(LRTSBook, cover)
WCDB_SYNTHESIZE(LRTSBook, update)

WCDB_SYNTHESIZE(LRTSBook, refId)

WCDB_SYNTHESIZE(LRTSBook, categoryName)
WCDB_SYNTHESIZE(LRTSBook, lastUpdateTime)

WCDB_SYNTHESIZE(LRTSBook, enterPlayType)

WCDB_SYNTHESIZE(LRTSBook, bParentId)
WCDB_SYNTHESIZE(LRTSBook, bCategoryId)

WCDB_SYNTHESIZE(LRTSBook, downloadedSectionCount)

WCDB_SYNTHESIZE(LRTSBook, recordId)
WCDB_SYNTHESIZE(LRTSBook, recordStatus)
WCDB_SYNTHESIZE(LRTSBook, like)
WCDB_SYNTHESIZE(LRTSBook, entityType)

WCDB_SYNTHESIZE(LRTSBook, extInfo)

WCDB_SYNTHESIZE(LRTSBook, strategy)
WCDB_SYNTHESIZE(LRTSBook, freeEndTime)
WCDB_SYNTHESIZE(LRTSBook, overEndTime)
WCDB_SYNTHESIZE(LRTSBook, updateState)

@end
