//
//  LRTSDBUserModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/9.
//

#import "LRTSDBUserModel.h"
#import <WCDB/WCDB.h>


@implementation LRTSDBUserModel

WCDB_IMPLEMENTATION(LRTSDBUserModel)

WCDB_SYNTHESIZE(LRTSDBUserModel, userId)

WCDB_SYNTHESIZE(LRTSDBUserModel, account)
WCDB_SYNTHESIZE(LRTSDBUserModel, token)
WCDB_SYNTHESIZE(LRTSDBUserModel, gender)
WCDB_SYNTHESIZE(LRTSDBUserModel, nickname)
WCDB_SYNTHESIZE(LRTSDBUserModel, cover)
WCDB_SYNTHESIZE(LRTSDBUserModel, backCover)
WCDB_SYNTHESIZE(LRTSDBUserModel, areaIds)
WCDB_SYNTHESIZE(LRTSDBUserModel, address)
WCDB_SYNTHESIZE(LRTSDBUserModel, desrc)
WCDB_SYNTHESIZE(LRTSDBUserModel, birthday)

WCDB_SYNTHESIZE(LRTSDBUserModel, phone)
WCDB_SYNTHESIZE(LRTSDBUserModel, email)
WCDB_SYNTHESIZE(LRTSDBUserModel, state)
WCDB_SYNTHESIZE(LRTSDBUserModel, purchaseTime)
WCDB_SYNTHESIZE(LRTSDBUserModel, point)
WCDB_SYNTHESIZE(LRTSDBUserModel, timeRemaining)
WCDB_SYNTHESIZE(LRTSDBUserModel, mSectionCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, sectionCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, grade)
WCDB_SYNTHESIZE(LRTSDBUserModel, coin)
WCDB_SYNTHESIZE(LRTSDBUserModel, newPoint)

WCDB_SYNTHESIZE(LRTSDBUserModel, receiveLetter)

WCDB_SYNTHESIZE(LRTSDBUserModel, questionA)
WCDB_SYNTHESIZE(LRTSDBUserModel, anwserA)
WCDB_SYNTHESIZE(LRTSDBUserModel, questionB)
WCDB_SYNTHESIZE(LRTSDBUserModel, anwserB)
WCDB_SYNTHESIZE(LRTSDBUserModel, isFollowLogin)
WCDB_SYNTHESIZE(LRTSDBUserModel, isFollow)

WCDB_SYNTHESIZE(LRTSDBUserModel, attentionCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, fansCount)

WCDB_SYNTHESIZE(LRTSDBUserModel, collectionCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, albumCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, bookCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, bbCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, bbReadCount)
WCDB_SYNTHESIZE(LRTSDBUserModel, collectReadCount)

WCDB_SYNTHESIZE(LRTSDBUserModel, ticketBalance)

WCDB_SYNTHESIZE(LRTSDBUserModel, isShowGuide)

//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )


//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )
//WCDB_SYNTHESIZE(LRTSDBUserModel, )


@end
