//
//  LRTSDBTecentO2AdModel.m
//  Kiwi
//
//  Created by JackJin on 2017/11/9.
//

#import "LRTSDBTecentO2AdModel.h"
#import <WCDB/WCDB.h>


@implementation LRTSDBTecentO2AdModel

WCDB_IMPLEMENTATION(LRTSDBTecentO2AdModel)

WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, width)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, height)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, scheduleId)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, gameId)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, locationId)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, channelId)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, desc)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, appName)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, sign)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, sourceUrl)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, pvUrl)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, cvUrl)
WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, downloadUrl)


//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
////
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )
//WCDB_SYNTHESIZE(LRTSDBTecentO2AdModel, )

@end
